[build]
  base = ""
  publish = "build/"
  command = "yarn build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"

  [headers.values]
    Basic-Auth = "mitstudents:mitstudents"